name: Python Quality Assurance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        # Options to wait for MySQL to be ready
        options: >-
          --health-cmd="mysqladmin ping -h localhost -P 3306 -u root -ptestpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Check out the code from your repository onto the machine
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the specific Python version
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install uv
      - name: Install uv
        run: pip install uv

      # Step 4: Install project's dependencies using uv
      - name: Install dependencies
        run: |
          # 4.1: Install the main project and its core dependencies
          uv pip install --system .
          # 4.2: Explicitely install development tools
          uv pip install --system pytest pytest-cov ruff

      # Step 5: Linter
      - name: Lint with ruff
        run: |
          # stop the build if there are any linter errors
          ruff check .
          # check formatting
          ruff format . --check

      # Step 6: Test with Pytest with coverage report
      - name: Test with pytest and generate coverage report
        env:
          DB_TYPE: mysql
          MYSQL_TEST_HOST: 127.0.0.1
          MYSQL_TEST_PORT: 3306
          MYSQL_TEST_USER: root
          MYSQL_TEST_PASSWORD: testpassword
          MYSQL_TEST_DB: test_db
        run: python -m pytest --cov=db_tools_pkg --cov-report=xml --cov-report=term-missing
