name: Python Quality Assurance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository onto the machine
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the specific Python version
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install uv
      - name: Install uv
        run: pip install uv

      # Step 4: Install project's dependencies using uv
      - name: Install dependencies
        run: uv pip install --system .[dev]

      # Step 5: Linter
      - name: Lint with ruff
        run: |
          # stop the build if there are any linter errors
          ruff check .
          # check formatting
          ruff format . --check

      # Step 6: Test with Pytest with coverage report
      - name: Test with pytest
        run: python -m pytest --cov=db_tools_pkg --cov-report=xml --cov-report=term-missing
